### ISSUE TITLE
Error when loading config

### ISSUE THREAD

**Issue by JonasKruckenberg** [small-tech/vite-plugin-sri#1]
Hey, I just checked out you plugin and it seems something is not quite right.
```
error when starting dev server:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: [...]/node_modules/@small-tech/vite-plugin-sri/index.js
require() of ES modules is not supported.
require() of [...]/node_modules/@small-tech/vite-plugin-sri/index.js from[...]/vite.config.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from [...]/node_modules/@small-tech/vite-plugin-sri/package.json.
```

I've never seen this before, but I guess it's because you module is an es6 module and nodes still has difficulties loading them natively?

I also checked both _vite.config.js_ and _vite.config.ts_, but there seems to be no difference.

> UPDATE: Setting "type":"module" on my project fixed the issue, but you should think about providing both a cjs and esm version, most people will be thrown off by this I think.

**Comment by valtism** [comment]
If you want a workaround until this gets published to `npm`, if you use the `patch-package` library you can patch the current version (`1.0.1`) with this patch to get things working. https://gist.github.com/valtism/f5eff35edb827f0dccf39f8e9347e6ce

This patch just takes the build output of the commonJS build and replaces the ESModule `index.js` file with its output. You should then be able to run the plugin without adding `"type": "module" to your `package.json`
